[[redirects]]
  from = "/api/*"
  to = "https://e-commerce-production-07f8.up.railway.app/api/v1/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; connect-src 'self' https://e-commerce-production-07f8.up.railway.app"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"