[[redirects]]
  from = "/api/*"
  to = "https://e-commerce-production-07f8.up.railway.app/api/v1:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Content-Type = "text/javascript"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"